//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoBot.Commands {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class MessagesCustom : global::System.Configuration.ApplicationSettingsBase {
        
        private static MessagesCustom defaultInstance = ((MessagesCustom)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MessagesCustom())));
        
        public static MessagesCustom Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test value of setting! 8!!!")]
        public string testSetting {
            get {
                return ((string)(this["testSetting"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VersionCommandAnswerMessage {
            get {
                return ((string)(this["VersionCommandAnswerMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Personal info whiped.")]
        public string ResetCommandAnswerMessage {
            get {
                return ((string)(this["ResetCommandAnswerMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HelpCommandPrefix {
            get {
                return ((string)(this["HelpCommandPrefix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("show the current bot version")]
        public string HelpCommandVersion {
            get {
                return ((string)(this["HelpCommandVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("delete the state data assigned to the current user")]
        public string HelpCommandReset {
            get {
                return ((string)(this["HelpCommandReset"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("list all bot commands")]
        public string HelpCommandHelp {
            get {
                return ((string)(this["HelpCommandHelp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>/start</string>
  <string>начать поиск</string>
  <string>искать штраф</string>
  <string>новый поиск</string>
  <string>сначала</string>
  <string>заново</string>
  <string>сброс</string>
  <string>выход</string>
  <string>искать ещё</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection StartSearchFinesCommands {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StartSearchFinesCommands"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>помощь</string>
  <string>помоги</string>
  <string>?</string>
  <string>help</string>
  <string>/?</string>
  <string>/help</string>
  <string>/помощь</string>
  <string>меню</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection HelpCommands {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["HelpCommands"]));
            }
        }
    }
}
